import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:printing/printing.dart';

/// Displays a generated PDF invoice using the [PdfPreview] widget.
///
/// The [PdfPreview] widget provides built-in share and print buttons
/// from the `printing` package.
class InvoicePreviewPage extends StatelessWidget {
  final Uint8List pdfBytes;
  final String title;

  const InvoicePreviewPage({
    super.key,
    required this.pdfBytes,
    this.title = 'Invoice',
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
        backgroundColor: const Color(0xFF1A1A1A),
      ),
      body: PdfPreview(
        // Return the already-generated bytes; no need to regenerate.
        build: (_) async => pdfBytes,
        allowPrinting: true,
        allowSharing: true,
        canChangeOrientation: false,
        canChangePageFormat: false,
        canDebug: false,
        pdfFileName: '${title.replaceAll(' ', '_')}.pdf',
      ),
    );
  }
}
